# gitlab-zh.yml
# git clone https://gitlab.com/xhang/gitlab.git
# cat gitlab/VERSION
# gitlab-ctl stop
# cd /root/gitlab
# git diff v10.0.2 v10.0.2-zh > ../10.0.2-zh.diff
# patch -d /opt/gitlab/embedded/service/gitlab-rails -p1 < 10.0.2-zh.diff
# gitlab-ctl start
# gitlab-ctl reconfigure

- hosts: local
  gather_facts: no
  remote_user: root

  tasks:
    - name: download gitlab_cn
      git:
        repo: https://gitlab.com/xhang/gitlab.git
        dest: /app/down/git/
    - name: diff gitlab_zh
      command: cd /app/down/git/gitlab/
      command: git diff v10.6.2 v10.6.2-zh > ../10.6.2-zh.diff
    - name: patch copy file to gitlab-ce
      command: cd /app/down/git/gitlab/
      command: patch -d /opt/gitlab/embedded/service/gitlab-rails -p1 < 10.6.2-zh.diff
    - name: stop gitlab
      command: gitlab-ctl stop
    - name: configure gitlab
      command: gitlab-ctl reconfigure
    - name: restart gitlab
      command: gitlab-ctl restart

