# gitlab.yml
# copy gitlab-ce.repo
# systemctl start postfix
# systemctl enable postfix
# gitlab-ctl reconfigure
# head -1 /opt/gitlab/version-manifest.txt
# 待开发, 配置
# nginx 端口号
# 访问域名

---
- hosts: local
  gather_facts: no
  remote_user: root

  tasks:
    - name: copy gitlab repo to yum repo
      copy:
        src: /app/data/ansible/books/application/gitlab-ce.repo
        dest: /etc/yum.repos.d/
        owner: root
        group: root
    - name: install dependeces postfix should be run
      yum: name=postfix

    - name: install gitlab-ce
      yum: name=gitlab-ce
      with_items:
        - curl
        - openssh-server
        - openssh-clients
        - cronie
    - name: copy config file
      copy:
        src: /app/data/ansible/books/application/gitlab.rb
        dest: /etc/gitlab/gitlab.rb
        backup: yes
    - name: start configure gitlab
      command: gitlab-ctl start && gitlab-ctl reconfigure && gitlab-ctl restart


