---

dependencies: []
galaxy_info:
  author: ccz
  description: jumpserver跳板机安装
  license: MIT
  min_ansible_version: 2.4
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  galaxy_tags:
    - jumpserver
