# publish-ssh-key.yml
# 1.export ANSIBLE_HOST_KEY_CHECKING=False  or vi /etc/ansible/ansible.cfg host_key_checking = False
# 2.ssh-keygen -t rsa -b 2048 -P '' -f /root/.ssh/id_rsa
#   renew ssh key: ssh-keygen -t rsa -f /root/.ssh/id_rsa_new
# 3.mkhosts
# 4.run playbook: ansible-playbook -i hosts publish-ssh-key-and-init-env.yml -k (-k is all hosts passwd, must be same!)

---
- hosts: all
  gather_facts: no

  tasks:
  - name: checking false
    shell: export ANSIBLE_HOST_KEY_CHECKING=False
#  - name: generate ssh key
#    shell: ssh-keygen -t rsa -b 2048 -P '' -f /root/.ssh/id_rsa
  - name: install ssh key - no login
    authorized_key: user=root 
                    key="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
                    state=present