- hosts: localhost
  vars_files:
    - vars.yml
  debug:
    msg: "{{item}}"
    vars_files:
      - vars.yml
    with_items: "{{cifaz_roles}}"
#  roles:
#    - role: "{{item}}"
#      vars_files:
#        - vars.yml
#      with_items: "{{cifaz_roles}}"

