# publish-ssh-key.yml
# 1.export ANSIBLE_HOST_KEY_CHECKING=False  or vi /etc/ansible/ansible.cfg host_key_checking = False
# 2.ssh-keygen -t rsa -b 2048 -P '' -f /root/.ssh/id_rsa
#   renew ssh key: ssh-keygen -t rsa -f /root/.ssh/id_rsa_new
# 3.mkhosts
# 4.run playbook: ansible-playbook -i hosts publish-ssh-key-and-init-env.yml -k (-k is all hosts passwd, must be same!)

---
- hosts: all
  gather_facts: no
  vars_files:
      - vars.yml
  roles:
    - role: tersmitten.ssh-keys
      when: enable_push_ssh_key
      vars:
        ssh_keys_private_keys:
          - owner: root
            src: "{{ssh_keys_dir}}/{{ssh_keys_priv_name}}"
        ssh_keys_public_keys:
          - owner: root
            src: "{{ssh_keys_dir}}/{{ssh_keys_pub_name}}"
        ssh_keys_authorized_keys:
          - owner: root
            src: "{{ssh_keys_dir}}/{{ssh_keys_pub_name}}"
  tasks:
     # 更改YUM
     - import_tasks: install-centos-aliyum.yml
     # 统一创建目录 安装依赖 更换中国时间
     - import_tasks: install-centos-init.yml

     - name: stop firewalld
       service:
         name: firewalld
         enabled: no
         state: stopped

     - name: stop selinux
       shell: setenforce 0

     - name: modify disabled selinux
       selinux:
         state: disabled
