---

- hosts: local
  vars_files:
    - vars.yml
  roles:
    - role: cifaz.generate-ssh-key
      when: do_push_ssh_key
    - role: tersmitten.ssh-keys
      vars:
        ssh_keys_private_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_priv_name}}"
        ssh_keys_public_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_pub_name}}"
        ssh_keys_authorized_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_pub_name}}"
      when: do_push_ssh_key
  tasks:
    - name: print somethings
      debug:
        msg: "hiiiiii"
