---
- hosts: local
  vars_files:
    - vars.yml
  roles:
    - role: cifaz.generate-ssh-key
      when: enable_generate_ssh_key

- hosts: local
  vars_files:
    - vars.yml
  roles:
    - role: tersmitten.ssh-keys
      when: enable_push_ssh_key
      vars:
        ssh_keys_private_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_priv_name}}"
        ssh_keys_public_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_pub_name}}"
        ssh_keys_authorized_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_pub_name}}"

    - role: srsp.oracle-java
      when: enable_oracle_java
      vars:
        java_version: "{{java_version}}"
        java_subversion: "{{java_subversion}}"
        java_build: "{{java_build}}"
#        jdk_tarball_hash: "{{jdk_tarball_hash}}"
        java_remove_download: "{{java_remove_download}}"
        java_set_javahome: "{{java_set_javahome}}"


  tasks:
    - name: print somethings
      debug:
        msg: "===== install ok ======"


