---
- hosts: local
  vars_files:
    - vars.yml
  roles:
    - role: cifaz.generate-ssh-key
      when: enable_generate_ssh_key

- hosts: local
  vars_files:
    - vars.yml
  roles:
    - role: tersmitten.ssh-keys
      vars:
        ssh_keys_private_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_priv_name}}"
        ssh_keys_public_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_pub_name}}"
        ssh_keys_authorized_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_pub_name}}"
      when: enable_push_ssh_key
    - role: williamyeh.oracle-java
      vars:
        java_version: 8
        java_subversion: 161
        java_build: 13

  tasks:
    - name: print somethings
      debug:
        msg: "hiiiiii"
