---
- hosts: local
  vars_files:
    - vars.yml
  roles:
    - role: cifaz.generate-ssh-key
      when: enable_generate_ssh_key

- hosts: all
  vars_files:
    - vars.yml
    - role: tersmitten.ssh-keys
      vars:
        ssh_keys_private_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_priv_name}}"
        ssh_keys_public_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_pub_name}}"
        ssh_keys_authorized_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_pub_name}}"
      when: enable_push_ssh_key

    - role: ansiblebit.oracle-java
      oracle_java_version: 8
      oracle_java_version_update: 161
      oracle_java_version_build: 13
      oracle_java_set_as_default: yes
      oracle_java_rpm_validate_certs: no

  tasks:
    - name: print somethings
      debug:
        msg: "hiiiiii"
