# install ssh key to all
---
- hosts: all
  vars_files:
    - vars.yml
  roles:
    - role: tersmitten.ssh-keys
      vars:
        ssh_keys_private_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_priv_name}}"
        ssh_keys_public_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_pub_name}}"
        ssh_keys_authorized_keys:
          - owner: root
            src: "{{ssh_key_dir}}/{{ssh_key_pub_name}}"
