---
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - role: geerlingguy.gitlab
      when: enable_gitlab
      vars:
        gitlab_external_url: "{{gitlab_external_url}}"
        gitlab_git_data_dir: "{{gitlab_git_data_dir}}"
        gitlab_backup_path: "{{gitlab_backup_path}}"
        gitlab_version: {{gitlab_version}}
        gitlab_nginx_listen_port: {{gitlab_nginx_listen_port}}
        gitlab_nginx_listen_https: "{{gitlab_nginx_listen_https}}"
    - role: cifaz.gitlab-zh
      when: enable_gitlab_zh



