---
- hosts: local
  gather_facts: no
  remote_user: root

  tasks:
    - name: Download JDK rpm
      get_url:
        url: "http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.rpm"
        dest: /app/down/jdk-8u161.rpm
        headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    - name: Install the downloaded jdk
      yum:
        name: /app/down/jdk-8u161.rpm
        state: present
      become: yes

