---
- hosts: localhost
  vars_files:
    - ../vars.yml
  roles:
    - role: geerlingguy.gitlab
      vars_files:
        - ../vars.yml
      when: enable_gitlab

    - role: cifaz.gitlab-zh
      vars_files:
        - ../vars.yml
      when: enable_gitlab_zh



