# tasks file for jenkins-centos

---
- name: Install JDK
  yum:
    name: "{{jenkins_jdk}}"
    update_cache: yes
  when: jenkins_jdk != "no" and jenkins_jdk
  register: result_install_jdk

- name: Add repository
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  register: result_add_repository

- name: Add jenkins-ci.org.key
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  register: result_add_rpm_key

- name: Install jenkins
  yum:
    name: jenkins
    update_cache: yes
  register: result_install_jenkins

- name: set JENKINS_PORT
  lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: "^JENKINS_PORT="
    line: 'JENKINS_PORT="{{jenkins_port}}"'
  when: jenkins_port is defined
  register: result_jenkins_port

- name: set JENKINS_LISTEN_ADDRESS
  lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: "^JENKINS_LISTEN_ADDRESS="
    line: 'JENKINS_LISTEN_ADDRESS="{{jenkins_listen_address}}"'
  when: jenkins_listen_address is defined
  register: result_jenkins_listen_address

- name: set JENKINS_ARGS
  lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: "^JENKINS_ARGS="
    line: 'JENKINS_ARGS="{{jenkins_args}}"'
  when: jenkins_args is defined
  register: result_jenkins_args

- name: Change jenkins state
  service:
    name: jenkins
    state: "{{jenkins_state}}"
  when: jenkins_state is defined and jenkins_state != "not restarted"

- name: Change jenkins state
  service:
    name: jenkins
    state: restarted
  when: jenkins_state is undefined and (result_install_jdk.changed or result_add_repository.changed or result_add_rpm_key.changed or result_install_jenkins.changed or result_jenkins_port.changed or result_jenkins_listen_address.changed or result_jenkins_args.changed)

- name: Change whether the service should start on boot
  service:
    name: jenkins
    enabled: "{{jenkins_enabled}}"
  when: jenkins_enabled is defined
