# mysql && create database jumpserver default charset 'utf8'; && grant all on jumpserver.* to 'jumpserver'@'127.0.0.1' identified by 'somepassword';

- name: create database jumperserver
  mysql_db:
    name: jumpserver

- name: create user and privilages
  mysql_user:
    name: jumpserver
    password: ccz2531
    priv: "jumpserver.*:ALL,GRANT"
    host_all: yes
    host: "%"

- name: config jumpserver
  copy:
    src: config.py
    dest: /opt/jumpserver/
    backup: yes
    force: yes

  #cd /opt/jumpserver && \cp config_example.py config.py

- name: generate database and datas
  shell: source /opt/py3/bin/activate && cd /opt/jumpserver/utils/ && /bin/bash make_migrations.sh
