- name: install jumperser requirements
  shell: yum -y install $(cat /opt/jumpserver/requirements/rpm_requirements.txt)

- name: install python requrements
  shell: pip install -r requirements.txt

  roles:
    - {role: DavidWittman.redis, tag: "dbredis", redis_bind: 127.0.0.1}
  roles:
    - geerlingguy.mysql

