---
- hosts: local
  gather_facts: no
  remote_user: root

  tasks:
    - name: Download JDK rpm
      get_url:
        url: "http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.rpm"
        dest: /app/down/jdk-8u161.rpm
        headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    - name: Install the downloaded jdk
      yum:
        name: /app/down/jdk-8u161.rpm
        state: present
      become: yes

    - name: check jdk variable
      shell: cat /etc/profile
      register: result

    #jdk_version 在变量文件中有定义
    - name: jdk variable configuration /etc/profile file
      shell: /bin/echo {{ item }} >> /etc/profile; source /etc/profile
      when: result.stdout.find('JAVA_HOME') == -1
      with_items:
         - export JAVA_HOME=/usr/java/jdk{{ jdk_version }}
         - export JAVA_BIN=/usr/java/jdk{{ jdk_version }}/bin
         - export PATH=$PATH:/usr/java/jdk{{ jdk_version }}/bin
         - export JRE_HOME=/usr/java/jdk{{ jdk_version }}/jre
         - export CLASSPATH=.:/usr/java/jdk{{ jdk_version }}/lib:/usr/java/jdk{{ jdk_version }}/jre/lib
         - export JAVA_HOME JAVA_BIN PATH JRE_HOME CLASSPATH